shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320

catalog:
  '@alova/wormhole': ^1.0.0

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
