shellEmulator: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 4320

packages:
  - core
  - template
  - docs

overrides:
  '@oevery/nuva': 'workspace:*'

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@iconify-json/lucide': ^1.2.111
  '@nuxt/content': ^3.6.3
  '@nuxt/icon': ^2.2.2
  '@nuxt/kit': ^4.4.6
  '@nuxt/ui': ^4.4.6
  '@tailwindcss/vite': ^4.3.0
  '@types/node': ^25.9.1
  '@vueuse/nuxt': ^14.1.0
  alova: ^3.5.1
  better-auth: ^1.6.0
  defu: ^6.1.4
  eslint: ^10.4.0
  eslint-plugin-format: ^2.0.1
  nuxt: ^4.4.6
  ohash: ^2.0.11
  tailwindcss: ^4.3.0
  typescript: ^6.0.3
  valibot: ^1.4.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
